Algoritmo "condição mais correta"

Var
valor:real


Inicio
      escreval("digite um numero")
      leia(valor)
      escreval("------------")

limpatela

         se(valor >10) entao
         escreva(valor," valor maior que 10")
         fimse

         se(valor<10)entao
         escreva(valor, " valor é menor que 10")
         fimse

         se(valor=10) entao
         escreva(valor," valor igual a 10")
         fimse




Fimalgoritmo
