Algoritmo "loginesenha"

Var
login, senha:caractere
loginarmazenado, senhaarmazenada:caractere
Inicio

loginarmazenado<-"alan"
senhaarmazenada<-"1234"

escreval("digite o login:")
leia(login)
escreval("digite a senha:")
leia(senha)

limpatela

se (login = loginarmazenado) e (senha = senhaarmazenada) entao
   escreval("bem-vindo")
senao
   escreval("login ou senha incorreta")
fimse




fimalgoritmo


 

