Algoritmo "compra a granel e em quantidade"

Var
nome, sexo, estadocivil,tempodecasamento: caractere

Inicio

escreva("Escreva seu nome:")
leia(nome)
escreva("escreva seu sexo:")
leia(sexo)
escreva("Qual seu estado civil?")
leia(estadocivil)


se (sexo = "f") e (estadocivil = "casada") entao
escreval("quanto tempo de casamento?")
leia(tempodecasamento)
fimse

escreval


Fimalgoritmo