Algoritmo "compra a granel e em quantidade"

Var

quantidade:real


Inicio

//Se quantidade for maior ou igual a 12 maçã custará 1.00
//se menor custará 1.30

escreval("Qual a quantidade de maçãs você quer comprar?")
leia(quantidade)




se quantidade >= 12 entao
escreval("O valor da compra é:",quantidade*1.00)
senao
escreval("O valor da compra é:",quantidade*1.30)
fimse



 

 


Fimalgoritmo